package mperry

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two 
 * terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 * 
 */
object P02 {

  def p = {
    val r = fib.takeWhile(_ <= 4000000).filter(n => n % 2 == 0).foldLeft (0) (_+_)
    assert(r == 4613732)
    println(r)
  }
  
  lazy val fib: Stream[Int] = {
    1 #:: 2 #:: fib.zip(fib.tail).map(p => p._1 + p._2)
  }
  
}